version: '3.4'

services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    container_name: pytorch_container
    volumes:
      - ./workdir:/workdir
    command: tail -f /dev/null

volumes:
  pytorch_data: